version: "3.8"

services:
  app_postgres:
    image: postgres:latest
    restart: always
    container_name: app_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
