version: "3.8"

services:
  app_postgres:
    image: postgres:latest
    restart: always
    container_name: app_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    networks:
      - app-tier
  app_jira:
    build:
      dockerfile: Dockerfile
    image: app_jira
    container_name: app_jira
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    networks:
      - app-tier
    environment:
      DB_HOST: app_postgres
      DB_PORT: 5432
    restart: always
    depends_on:
      - app_postgres

networks:
  app-tier:
    driver: bridge
